version: "3"
services:
    centos:
        image: centos:8
        # ports:
        #   - 8002:8002
        # restart: always
        #restart: always
        build: .
        container_name: 'centos_plane'
        #working_dir: '/root/'
        volumes:
            - .\opt:/usr/local/bin
        tty: true
        
